# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sim_api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsim_api.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"\x86\x01\n\x0fSimulationState\x12*\n\x05state\x18\x02 \x01(\x0e\x32\x1b.grpc.SimulationState.State\x12\x0f\n\x07tick_id\x18\x03 \x01(\x05\"6\n\x05State\x12\r\n\tUNDEFINED\x10\x00\x12\x07\n\x03NEW\x10\x01\x12\n\n\x06\x41\x43TIVE\x10\x06\x12\t\n\x05\x45NDED\x10\x07\"4\n\rVehicleUpdate\x12\x0f\n\x07tick_id\x18\x01 \x01(\x05\x12\x12\n\nvehicle_id\x18\x02 \x01(\x05\x32x\n\x07OpenCDA\x12=\n\x15SimulationStateStream\x12\x0b.grpc.Empty\x1a\x15.grpc.SimulationState0\x01\x12.\n\nSendUpdate\x12\x13.grpc.VehicleUpdate\x1a\x0b.grpc.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sim_api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=23
  _EMPTY._serialized_end=30
  _SIMULATIONSTATE._serialized_start=33
  _SIMULATIONSTATE._serialized_end=167
  _SIMULATIONSTATE_STATE._serialized_start=113
  _SIMULATIONSTATE_STATE._serialized_end=167
  _VEHICLEUPDATE._serialized_start=169
  _VEHICLEUPDATE._serialized_end=221
  _OPENCDA._serialized_start=223
  _OPENCDA._serialized_end=343
# @@protoc_insertion_point(module_scope)
